# notebook pour l'implémentation de nouvelles fonction pour le module python
notebook pour tester l'implémentation des nouvelles fonctions du module benford.py

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os, sys, math

import pybenford as ben

In [2]:
data = pd.read_csv("tests/Data_exp/1512006-Calbicans-QUANTI_raw_abundance.csv", sep=",", header=None)
print(data.shape)
data.head()

(2356, 12)


0             1             2             3             4   \
0  9.325899e+04  2.765206e+04  6.973654e+04  6.309967e+04  2.252522e+04   
1  5.042612e+07  1.592204e+07  4.388571e+07  1.824970e+07  1.596605e+07   
2  0.000000e+00  0.000000e+00  6.015709e+03  2.413695e+03  0.000000e+00   
3  1.560630e+07  7.262593e+06  4.718013e+06  2.570901e+06  1.629196e+06   
4  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   

             5             6             7             8             9   \
0  5.307728e+04  9.088306e+04  2.035561e+04  0.000000e+00  0.000000e+00   
1  1.566419e+07  2.563818e+07  2.666071e+07  1.431299e+07  2.617207e+07   
2  0.000000e+00  0.000000e+00  0.000000e+00  2.132027e+03  4.891291e+04   
3  2.344451e+06  2.178284e+07  2.715498e+07  1.042588e+06  2.429717e+06   
4  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   

             10            11  
0  1.021926e+05  1.794098e+05  
1  2.847710e+07  4.051467e+07  
2  2.974154e+04  4.261914e+04  
3  1.749820e+06  2.306792e+06  
4  2.729096e+03  3.448312e+04

In [3]:
# données dans un array d'une dimmenssion
exp_numbers = data.values.reshape(data.shape[0]*data.shape[1])
print(exp_numbers.shape)
exp_numbers = np.array(exp_numbers, dtype=int)

(28272,)


In [4]:
# Remove 0
exp_numbers = exp_numbers[ exp_numbers > 0 ]
exp_numbers.shape

(26919,)

In [5]:
first_digit = ben.count_first_digit(exp_numbers, nb_digit=1)
first_digit

array([7942, 4691, 3273, 2642, 2176, 1885, 1638, 1390, 1282])

In [6]:
first_digit_norm = ben.normalize_first_digit(first_digit)
first_digit_norm

array([0.29503325, 0.17426353, 0.12158698, 0.09814629, 0.0808351 ,
       0.07002489, 0.06084921, 0.05163639, 0.04762435])

## Fonction POM (Physical Order of Magnitude)

In [7]:
ben.calculate_pom(exp_numbers)

POM : 885178948.0


885178948.0

## fonction OOM (Order of Magnitude)

In [8]:
ben.calculate_oom(exp_numbers)

POM : 885178948.0
OOM : 8.94703107665586


8.94703107665586

## Fonction SSD (Sum of Squares Deviation)

In [9]:
ben.calculate_ssd(first_digit_norm, ben.get_theoretical_freq_benford())

SDD : 0.7615741694551663


0.7615741694551663

## Fonction RMSSD (Root Mean Sum of Square Deviation)

In [10]:
ben.calculate_rmssd(first_digit_norm, ben.get_theoretical_freq_benford())

SDD : 0.7615741694551663
RMSSD : 0.2908940565939517


0.2908940565939517

## Fonction chisquare test (sans bootstrap)

In [11]:
ben.chi2_test(exp_numbers, ben.get_theoretical_freq_benford())

statistics : 17.274209428053247 ; p-value : 0.027377095106173994


(17.274209428053247, 0.027377095106173994)

#### avec bootstrap

In [12]:
ben.calculate_bootstrap_chi2(exp_numbers, ben.get_theoretical_freq_benford(), nb_digit=1,
                            type_test=0)

statistics : 8.400410263951448 ; p-value : 0.3953653873747007


(8.400410263951448, 0.3953653873747007)

## Fonction G-test (sans bootstrap)

In [13]:
ben.g_test(exp_numbers, ben.get_theoretical_freq_benford())

[7942 4691 3273 2642 2176 1885 1638 1390 1282]
[8103.42645328 4740.20060252 3363.22585076 2608.72064016 2131.47996236
 1802.14063007 1561.08522069 1376.97475176 1231.7458884 ]
statistics : 17.16574732677782 ; p-value : 0.02842870395537781


(17.16574732677782, 0.02842870395537781)

## Fonction calcul de la distance de Hellinger

très sensible aux petites déviation de la loi de Benford

In [14]:
ben.calculate_dist_hellinger(first_digit_norm, ben.get_theoretical_freq_benford())

Hellinger distance : 0.006776437622267773


0.006776437622267773

## Fonction calcul de la distance de Kullback & Leibler

In [15]:
ben.calculate_dist_k_and_l(first_digit_norm, ben.get_theoretical_freq_benford())

Kullback & Leibler distance : 0.0001384707704922912


0.0001384707704922912

# Test sur la taille des protéines de swissProt

In [16]:
data2 = pd.read_csv("tests/Prot_tot_uniprot/uniprot-reviewed yes.tab", sep="\t",
                   header=0)
print(data.shape)
data.head()

(2356, 12)


0             1             2             3             4   \
0  9.325899e+04  2.765206e+04  6.973654e+04  6.309967e+04  2.252522e+04   
1  5.042612e+07  1.592204e+07  4.388571e+07  1.824970e+07  1.596605e+07   
2  0.000000e+00  0.000000e+00  6.015709e+03  2.413695e+03  0.000000e+00   
3  1.560630e+07  7.262593e+06  4.718013e+06  2.570901e+06  1.629196e+06   
4  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   

             5             6             7             8             9   \
0  5.307728e+04  9.088306e+04  2.035561e+04  0.000000e+00  0.000000e+00   
1  1.566419e+07  2.563818e+07  2.666071e+07  1.431299e+07  2.617207e+07   
2  0.000000e+00  0.000000e+00  0.000000e+00  2.132027e+03  4.891291e+04   
3  2.344451e+06  2.178284e+07  2.715498e+07  1.042588e+06  2.429717e+06   
4  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   

             10            11  
0  1.021926e+05  1.794098e+05  
1  2.847710e+07  4.051467e+07  
2  2.974154e+04  4.261914e+04  
3  1.749820e+06  2.306792e+06  
4  2.729096e+03  3.448312e+04

In [17]:
prot_len = data2["Entry Length"]
prot_len

Q8K9I1     960
Q664P8     255
Q66K14    1250
Q8E4B4     239
B3CQ06     426
          ... 
C3L855     410
P41413    1809
B7HED5     394
B1IUE0     408
Q1KXU1      31
Name: Entry Length, Length: 564638, dtype: int64

In [18]:
# fonction pom :
ben.calculate_pom(prot_len)
# fonction oom :
ben.calculate_oom(prot_len)

POM : 17606.5
POM : 17606.5
OOM : 4.245673031051872


4.245673031051872

In [19]:
d_obs = ben.count_first_digit(prot_len)
# fonction ssd :
ben.calculate_ssd(ben.normalize_first_digit(d_obs), ben.get_theoretical_freq_benford())
# fonction rmssd :
ben.calculate_rmssd(ben.normalize_first_digit(d_obs), ben.get_theoretical_freq_benford())

SDD : 88.79459235866496
SDD : 88.79459235866496
RMSSD : 3.1410294200515603


3.1410294200515603

In [20]:
# fonction Hellinger distance0.013833265465795642
ben.calculate_dist_hellinger(ben.normalize_first_digit(d_obs), ben.get_theoretical_freq_benford())

Hellinger distance : 0.027956872229815403


0.027956872229815403

In [21]:
# fonction K&L distance
ben.calculate_dist_k_and_l(ben.normalize_first_digit(d_obs), ben.get_theoretical_freq_benford())

Kullback & Leibler distance : 0.013833265465795618


0.013833265465795618

In [22]:
## test mise à jour count_first_digit

In [23]:
numbers = [-15.01, -0.025, 0.0000325, 0.0045004508, -0.005500145, -15]

In [24]:
fd_numbers = ben.count_first_digit(numbers)
fd_numbers

array([2, 1, 1, 1, 1, 0, 0, 0, 0])

In [25]:
ben.calculate_dist_k_and_l(ben.get_theoretical_freq_benford(), ben.get_theoretical_freq_benford())

Kullback & Leibler distance : 0.0


0.0

In [26]:
ben.calculate_dist_hellinger(ben.get_theoretical_freq_benford(), ben.get_theoretical_freq_benford())

Hellinger distance : 0.0


0.0

In [27]:
f_obs = [1/9]
f_obs = f_obs * 9
f_obs

[0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111]

In [28]:
ben.calculate_dist_hellinger(f_obs, ben.get_theoretical_freq_benford())

Hellinger distance : 0.10317283367839158


0.10317283367839158

In [29]:
ben.calculate_bootstrap_chi2(prot_len, ben.get_theoretical_freq_benford(), 1)

statistics : 72.81598919567465 ; p-value : 1.3486445363343955e-12


(72.81598919567465, 1.3486445363343955e-12)